function C = C_swing_jump_win(in1,in2,in3)
%C_SWING_JUMP_WIN
%    C = C_SWING_JUMP_WIN(IN1,IN2,IN3)

<<<<<<< HEAD
%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    14-Nov-2022 15:31:52
=======
%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    15-Nov-2022 16:12:41
>>>>>>> b04f7ebf989931bc421b2abf1f233498fc2f36bf

y = in1(1,:);
C = y;
