function C = C_swing_jump_win(in1,in2,in3)
%C_SWING_JUMP_WIN
%    C = C_SWING_JUMP_WIN(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    31-Oct-2022 16:57:46

y = in1(1,:);
C = y;
