function C = C_swing_jump_win(in1,in2,in3)
%C_SWING_JUMP_WIN
%    C = C_SWING_JUMP_WIN(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
<<<<<<< Updated upstream
%    06-Nov-2022 19:22:39
=======
%    10-Nov-2022 10:12:12
>>>>>>> Stashed changes

y = in1(1,:);
C = y;
