function COM = COM_swing_jump_win(in1,in2)
%COM_swing_jump_win
%    COM = COM_swing_jump_win(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    29-Nov-2022 14:50:50

c0 = in2(6,:);
c1 = in2(7,:);
c2 = in2(8,:);
c3 = in2(9,:);
c4 = in2(10,:);
dtha = in1(6,:);
dthh = in1(7,:);
dths = in1(8,:);
dy = in1(5,:);
l1 = in2(2,:);
l2 = in2(3,:);
l3 = in2(4,:);
l4 = in2(5,:);
m0 = in2(11,:);
m1 = in2(12,:);
m2 = in2(13,:);
m3 = in2(14,:);
m4 = in2(15,:);
m5 = in2(16,:);
tha = in1(2,:);
thh = in1(3,:);
ths = in1(4,:);
y = in1(1,:);
t2 = cos(thh);
t3 = cos(ths);
t4 = sin(thh);
t5 = sin(ths);
t12 = -thh;
t13 = -y;
t21 = m0+m1+m2+m3+m4+m5;
t6 = c1.*t2;
t7 = l1.*t2;
t8 = l2.*t2;
t9 = c1.*t4;
t10 = l1.*t4;
t11 = l2.*t4;
t14 = c2.*m2.*t2;
t15 = c4.*m4.*t5;
t16 = l4.*m5.*t5;
t17 = t12+tha;
t24 = 1.0./t21;
t18 = -t11;
t19 = cos(t17);
t20 = sin(t17);
t22 = c0.*t19;
t23 = c0.*t20;
COM = [t24.*(t14+t15+t16-m1.*(t6-t8)+m0.*(-t7+t8+t22));t24.*(m3.*(c3+y)+m4.*(l3+y-c4.*t3)+m5.*(l3+y-l4.*t3)-m1.*(t9+t11+t13)+m2.*(y-c2.*t4)-m0.*(t10+t11+t13+t23));dthh.*t24.*(m1.*(t9+t18)+m0.*(t10+t18+t23)-c2.*m2.*t4)+dths.*t24.*(c4.*m4.*t3+l4.*m5.*t3)-dtha.*m0.*t23.*t24;dy-dthh.*t24.*(t14+m1.*(t6+t8)+m0.*(t7+t8-t22))+dths.*t24.*(t15+t16)-dtha.*m0.*t22.*t24];
