function dC = dC_swing_jump_win(in1,in2,in3)
%dC_swing_jump_win
%    dC = dC_swing_jump_win(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    28-Nov-2022 16:14:19

dy = in1(5,:);
dC = dy;
