function dC = dC_swing_jump_win(in1,in2,in3)
%DC_SWING_JUMP_WIN
%    DC = DC_SWING_JUMP_WIN(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    06-Nov-2022 19:22:39

dy = in1(5,:);
dC = dy;
