function Ja = J_ank_swing_jump_win(in1,in2)
%J_ANK_SWING_JUMP_WIN
%    JA = J_ANK_SWING_JUMP_WIN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    10-Nov-2022 10:12:13

Ja = reshape([0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,4]);
