function Ja = J_ank_swing_jump_win(in1,in2)
%J_ank_swing_jump_win
%    Ja = J_ank_swing_jump_win(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    07-Nov-2022 17:09:55

Ja = reshape([0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,4]);
