function Jf = J_finger_swing_jump_win(in1,in2)
%J_FINGER_SWING_JUMP_WIN
%    JF = J_FINGER_SWING_JUMP_WIN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    15-Nov-2022 16:12:44

l4 = in2(5,:);
ths = in1(4,:);
Jf = reshape([0.0,1.0,0.0,0.0,0.0,0.0,l4.*cos(ths),l4.*sin(ths)],[2,4]);
