function Jh = J_hip_swing_jump_win(in1,in2)
%J_HIP_SWING_JUMP_WIN
%    JH = J_HIP_SWING_JUMP_WIN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    15-Nov-2022 16:01:37

Jh = reshape([0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,4]);
