function Jh = J_hip_swing_jump_win(in1,in2)
%J_hip_swing_jump_win
%    Jh = J_hip_swing_jump_win(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    11-Nov-2022 17:22:49

Jh = reshape([0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,4]);
