function Jt = J_toe_swing_jump_win(in1,in2)
%J_TOE_SWING_JUMP_WIN
%    JT = J_TOE_SWING_JUMP_WIN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
<<<<<<< Updated upstream
%    06-Nov-2022 19:22:40
=======
%    10-Nov-2022 10:12:13
>>>>>>> Stashed changes

l0 = in2(1,:);
tha = in1(2,:);
Jt = reshape([0.0,1.0,-l0.*sin(tha),l0.*cos(tha),0.0,0.0,0.0,0.0],[2,4]);
