function out1 = r_ank_swing_jump_win(in1,in2)
%R_ANK_SWING_JUMP_WIN
%    OUT1 = R_ANK_SWING_JUMP_WIN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    07-Nov-2022 16:28:39

y = in1(1,:);
out1 = [0.0;y];
