function out1 = r_finger_swing_jump_win(in1,in2)
%R_FINGER_SWING_JUMP_WIN
%    OUT1 = R_FINGER_SWING_JUMP_WIN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    15-Nov-2022 16:12:43

l3 = in2(4,:);
l4 = in2(5,:);
ths = in1(4,:);
y = in1(1,:);
out1 = [l4.*sin(ths);l3+y-l4.*cos(ths)];
