function out1 = r_heel_swing_jump_win(in1,in2)
%R_HEEL_SWING_JUMP_WIN
%    OUT1 = R_HEEL_SWING_JUMP_WIN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    28-Nov-2022 13:53:31

l1 = in2(2,:);
l2 = in2(3,:);
le1 = in2(23,:);
tha = in1(2,:);
thh = in1(3,:);
y = in1(1,:);
t2 = cos(thh);
t3 = sin(thh);
t4 = -thh;
t5 = t4+tha;
out1 = [-l1.*t2+l2.*t2-le1.*cos(t5);y-l1.*t3-l2.*t3+le1.*sin(t5)];
