function out1 = r_toe_swing_jump_win(in1,in2)
%R_TOE_SWING_JUMP_WIN
%    OUT1 = R_TOE_SWING_JUMP_WIN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    07-Nov-2022 16:28:38

l0 = in2(1,:);
tha = in1(2,:);
y = in1(1,:);
out1 = [l0.*cos(tha);y+l0.*sin(tha)];
