function out1 = v_finger_swing_jump_win(in1,in2)
%V_FINGER_SWING_JUMP_WIN
%    OUT1 = V_FINGER_SWING_JUMP_WIN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    15-Nov-2022 16:12:43

dths = in1(8,:);
dy = in1(5,:);
l4 = in2(5,:);
ths = in1(4,:);
out1 = [dths.*l4.*cos(ths);dy+dths.*l4.*sin(ths)];
