function out1 = v_heel_swing_jump_win(in1,in2)
%V_HEEL_SWING_JUMP_WIN
%    OUT1 = V_HEEL_SWING_JUMP_WIN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    28-Nov-2022 14:43:55

dtha = in1(6,:);
dthh = in1(7,:);
dy = in1(5,:);
l1 = in2(2,:);
l2 = in2(3,:);
le1 = in2(23,:);
tha = in1(2,:);
thh = in1(3,:);
t2 = cos(thh);
t3 = sin(thh);
t4 = -thh;
t5 = t4+tha;
t6 = cos(t5);
t7 = sin(t5);
out1 = [-dthh.*(-l1.*t3+l2.*t3+le1.*t7)+dtha.*le1.*t7;dy-dthh.*(l1.*t2+l2.*t2+le1.*t6)+dtha.*le1.*t6];
