function out1 = v_hip_swing_jump_win(in1,in2)
%V_HIP_SWING_JUMP_WIN
%    OUT1 = V_HIP_SWING_JUMP_WIN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    14-Nov-2022 15:31:54

dy = in1(5,:);
out1 = [0.0;dy];
