function out1 = v_hip_swing_jump_win(in1,in2)
%V_HIP_SWING_JUMP_WIN
%    OUT1 = V_HIP_SWING_JUMP_WIN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    28-Nov-2022 14:43:56

dy = in1(5,:);
out1 = [0.0;dy];
